// AUTO-GENERATED from private/docs/timeline_wave{2,3}.csv.
// Don't hand-edit; regenerate with scripts/regen-timeline.py.
//
// Each entry corresponds to one 'Alert #' row in the source CSVs.
// Together these define every automated message Project LITe sends.

import type { Channel, WaveYear } from "@/types";

export type AlertKind =
  | "athome_sms"
  | "athome_email"
  | "sts1_invite"
  | "sts1_followup"
  | "sts2_invite"
  | "sts2_followup"
  | "ema_enable"
  | "ema_prompt"
  | "payment_email"
  | "payment_followup"
  | "payment_expire"
  | "other";

export interface TimelineAlert {
  alertId: number;
  wave: WaveYear;
  kind: AlertKind;
  instrument: string;
  trigger: string | null;
  condition: string | null;
  sendDateSpec: string | null;
  destinationSpec: string | null;
  channels: Channel[];
  emaKey: string | null;
  message: string | null;
}

function parseChannels(spec: string | null): Channel[] {
  if (!spec) return [];
  const s = spec.toLowerCase();
  const out: Channel[] = [];
  if (s.includes("phone") || s.includes("ema_phone")) out.push("sms");
  if (s.includes("email")) out.push("email");
  return out;
}

const RAW: Omit<TimelineAlert, "channels">[] = [
  {
    alertId: 48,
    wave: 2 as WaveYear,
    kind: "sts1_invite",
    instrument: "Screen Time Auto Invite 1.1",
    trigger: null,
    condition: "[screen_time_y2_arm_1][screen_time_cycle_1]=1AND[screen_time_y2_arm_1][screen_time_1_complete]<>2",
    sendDateSpec: "[screen_time_y2_arm_1][screen_time_1_1_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending a brief 2-3 minute at screen-time survey to complete. We also want to remind you that for sticking with us and completing these surveys you will be compensated with $70 after 10 months. 1/9 [screen_time_y2_arm_1][survey-link:screen_time_1] THERE WILL BE DAILY AUTOMATED REMINDERS FOR THE NEXT WEEK UNTIL THE SURVEY IS COMPLETE",
  },
  {
    alertId: 49,
    wave: 2 as WaveYear,
    kind: "sts1_invite",
    instrument: "Screen Time Auto Invite 1.2",
    trigger: null,
    condition: "[screen_time_y2_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y2_arm_1][screen_time_2_complete]<>2",
    sendDateSpec: "[screen_time_y2_arm_1][screen_time_1_2_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending a brief 2-3 minute at screen-time survey to complete. We also want to remind you that for sticking with us and completing these surveys you will be compensated with $70 after 10 months. 2/9 [screen_time_y2_arm_1][survey-link:screen_time_2] THERE WILL BE DAILY AUTOMATED REMINDERS FOR THE NEXT WEEK UNTIL THE SURVEY IS COMPLETE",
  },
  {
    alertId: 50,
    wave: 2 as WaveYear,
    kind: "sts1_invite",
    instrument: "Screen Time Auto invite 1.3",
    trigger: null,
    condition: "[screen_time_y2_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y2_arm_1][screen_time_3_complete]<>2",
    sendDateSpec: "[screen_time_y2_arm_1][screen_time_1_3_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending a brief 2-3 minute at screen-time survey to complete. We also want to remind you that for sticking with us and completing these surveys you will be compensated with $70 after 10 months. 3/9 [screen_time_y2_arm_1][survey-link:screen_time_3] THERE WILL BE DAILY AUTOMATED REMINDERS FOR THE NEXT WEEK UNTIL THE SURVEY IS COMPLETE",
  },
  {
    alertId: 51,
    wave: 2 as WaveYear,
    kind: "sts1_invite",
    instrument: "Screen time Auto invite 1.4",
    trigger: null,
    condition: "[screen_time_y2_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y2_arm_1][screen_time_4_complete]<>2",
    sendDateSpec: "[screen_time_y2_arm_1][screen_time_1_4_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending a brief 2-3 minute at screen-time survey to complete. We also want to remind you that for sticking with us and completing these surveys you will be compensated with $70 after 10 months. 4/9 [screen_time_y2_arm_1][survey-link:screen_time_4] THERE WILL BE DAILY AUTOMATED REMINDERS FOR THE NEXT WEEK UNTIL THE SURVEY IS COMPLETE",
  },
  {
    alertId: 52,
    wave: 2 as WaveYear,
    kind: "sts1_invite",
    instrument: "Screen Time Auto Invite 1.5",
    trigger: null,
    condition: "[screen_time_y2_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y2_arm_1][screen_time_5_complete]<>2",
    sendDateSpec: "[screen_time_y2_arm_1][screen_time_1_5_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending a brief 2-3 minute at screen-time survey to complete. We also want to remind you that for sticking with us and completing these surveys you will be compensated with $70 after 10 months. 5/9 [screen_time_y2_arm_1][survey-link:screen_time_5] THERE WILL BE DAILY AUTOMATED REMINDERS FOR THE NEXT WEEK UNTIL THE SURVEY IS COMPLETE",
  },
  {
    alertId: 53,
    wave: 2 as WaveYear,
    kind: "sts1_invite",
    instrument: "Screen Time Auto Invite 1.6",
    trigger: null,
    condition: "[screen_time_y2_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y2_arm_1][screen_time_6_complete]<>2",
    sendDateSpec: "[screen_time_y2_arm_1][screen_time_1_6_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending a brief 2-3 minute at screen-time survey to complete. We also want to remind you that for sticking with us and completing these surveys you will be compensated with $70 after 10 months. 6/9 [screen_time_y2_arm_1][survey-link:screen_time_6] THERE WILL BE DAILY AUTOMATED REMINDERS FOR THE NEXT WEEK UNTIL THE SURVEY IS COMPLETE",
  },
  {
    alertId: 54,
    wave: 2 as WaveYear,
    kind: "sts1_followup",
    instrument: "Screen Time Follow Up 1.1",
    trigger: null,
    condition: "[screen_time_y2_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y2_arm_1][screen_time_1_complete]<>2",
    sendDateSpec: "1 days after [screen_time_y2_arm_1][screen_time_1_1_date].   Repeat every day  Send up to 6 times total",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hello, we just wanted to follow up about the screentime survey. Whenever you get the chance can you please fill out the survey? - [screen_time_y2_arm_1][survey-link:screen_time_1] If you opened the survey but are still receiving the message, it it because you likely left it incomplete - please restart the survey ( this is an automated reminder and it will send for the next week - feel free to respond and let us know if there is a reason you can't get to it this month)",
  },
  {
    alertId: 55,
    wave: 2 as WaveYear,
    kind: "sts1_followup",
    instrument: "Screen Time Follow Up 1.2",
    trigger: null,
    condition: "[screen_time_y2_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y2_arm_1][screen_time_2_complete]<>2",
    sendDateSpec: "1 days after [screen_time_y2_arm_1][screen_time_1_2_date].   Repeat every day  Send up to 6 times total",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hello, we just wanted to follow up about the screentime survey. Whenever you get the chance can you please fill out the survey? [screen_time_y2_arm_1][survey-link:screen_time_2] If you opened the survey but are still receiving the message, it it because you likely left it incomplete - please restart the survey ( this is an automated reminder and it will send for the next week - feel free to respond and let us know if there is a reason you can't get to it this month)",
  },
  {
    alertId: 56,
    wave: 2 as WaveYear,
    kind: "sts1_followup",
    instrument: "Screen Time Follow Up 1.3",
    trigger: null,
    condition: "[screen_time_y2_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y2_arm_1][screen_time_3_complete]<>2",
    sendDateSpec: "1 days after [screen_time_y2_arm_1][screen_time_1_3_date].   Repeat every day  Send up to 6 times total",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hello, we just wanted to follow up about the screentime survey. Whenever you get the chance can you please fill out the survey? [screen_time_y2_arm_1][survey-link:screen_time_3] If you opened the survey but are still receiving the message, it it because you likely left it incomplete - please restart the survey. ( this is an automated reminder and it will send for the next week - feel free to respond and let us know if there is a reason you can't get to it this month)",
  },
  {
    alertId: 57,
    wave: 2 as WaveYear,
    kind: "sts1_followup",
    instrument: "Screen Time Follow Up 1.4",
    trigger: null,
    condition: "[screen_time_y2_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y2_arm_1][screen_time_4_complete]<>2",
    sendDateSpec: "1 days after [screen_time_y2_arm_1][screen_time_1_4_date].   Repeat every day  Send up to 6 times total",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hello, we just wanted to follow up about the screentime survey. Whenever you get the chance can you please fill out the survey? [screen_time_y2_arm_1][survey-link:screen_time_4] If you opened the survey but are still receiving the message, it it because you likely left it incomplete - please restart the survey.",
  },
  {
    alertId: 58,
    wave: 2 as WaveYear,
    kind: "sts1_followup",
    instrument: "Screen Time Follow Up 1.5",
    trigger: null,
    condition: "[screen_time_y2_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y2_arm_1][screen_time_5_complete]<>2",
    sendDateSpec: "1 days after [screen_time_y2_arm_1][screen_time_1_5_date].   Repeat every day  Send up to 6 times total",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hello, we just wanted to follow up about the screentime survey. Whenever you get the chance can you please fill out the survey? [screen_time_y2_arm_1][survey-link:screen_time_5] If you opened the survey but are still receiving the message, it it because you likely left it incomplete - please restart the survey. ( this is an automated reminder and it will send for the next week - feel free to respond and let us know if there is a reason you can't get to it this month)",
  },
  {
    alertId: 59,
    wave: 2 as WaveYear,
    kind: "sts1_followup",
    instrument: "Screen Time Follow Up 1.6",
    trigger: null,
    condition: "[screen_time_y2_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y2_arm_1][screen_time_6_complete]<>2",
    sendDateSpec: "1 days after [screen_time_y2_arm_1][screen_time_1_6_date].   Repeat every day  Send up to 6 times total",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hello, we just wanted to follow up about the screentime survey. Whenever you get the chance can you please fill out the survey? [screen_time_y2_arm_1][survey-link:screen_time_6] If you opened the survey but are still receiving the message, it it because you likely left it incomplete - please restart the survey ( this is an automated reminder and it will send for the next week - feel free to respond and let us know if there is a reason you can't get to it this month)",
  },
  {
    alertId: 60,
    wave: 2 as WaveYear,
    kind: "athome_sms",
    instrument: "At-Home Survey Send (Text)",
    trigger: null,
    condition: "[visit_1_y2_arm_1][break_1_complete]=2",
    sendDateSpec: "3 hours, 45 minutes after [visit_1_y2_arm_1][timestamp_athome]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending an 8 section, 10-15 minute at-home survey section to complete. We will reach out to schedule the second visit once this survey has been completed: [athome_measures_y2_arm_1][survey-link:texi]",
  },
  {
    alertId: 61,
    wave: 2 as WaveYear,
    kind: "athome_email",
    instrument: "At-Home Survey Send (Email)",
    trigger: null,
    condition: "[visit_1_y2_arm_1][break_1_complete]=2",
    sendDateSpec: "3 hours, 45 minutes after [visit_1_y2_arm_1][timestamp_athome]",
    destinationSpec: "[preenrollment_arm_1][email]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending an 8 section, 10-15 minute at-home survey section to complete. We will reach out to schedule the second visit once this survey has been completed: [athome_measures_y2_arm_1][survey-link:texi] Project LITe Team",
  },
  {
    alertId: 63,
    wave: 2 as WaveYear,
    kind: "ema_enable",
    instrument: "EMA Y1 Enable",
    trigger: "4 months after invite 1.6 on the first 1st of the month",
    condition: "// Fires BEFORE the participant has enabled. The enable survey is where they set\n// [ema_y2_arm_1][lite_server_ema_enable] (the enable field) AND choose\n// [ema_y2_arm_1][ema_phone] — the phone number they want the EMA texts sent to.\n[ema_y2_arm_1][lite_server_ema_enable]<>1  // not yet enabled",
    sendDateSpec: "3 days, 8 hours before [ema_y2_arm_1][ema_start_day]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]",
    emaKey: null,
    message: "Hi [preenrollment_arm_1][first_name]! This is the project LITe Team.\n\n\nWe are beginning our social check next week on Monday. This will be a 10 day period, where we will be sending you 2 or 3 surveys a day, at random times. If you complete enough of them we will send you 70 dollars.\n\n\nPLEASE CLICK THIS LINK TO ENABLE THE SOCIAL CHECK:  [ema_y2_arm_1][survey-link:ema_participant_confirmation]",
  },
  {
    alertId: 64,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Monday 1 7:34 AM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: "[ema_y2_arm_1][ema_m1_734]",
    destinationSpec: "[ema_y2_arm_1][ema_phone]",
    emaKey: "ema_m1_734",
    message: "Hi [preenrollment_arm_1][first_name]!\n\nThis is a PROJECT LITe social check survey! It is meant to gauge your experience at this moment - and should only take 2-3 minutes to complete!\n\n\n\n[ema_y2_arm_1][survey-link:ema_report_1]\n\n\n**IF 30 MINUTES HAS PASSED SINCE YOU RECEIVED THIS SURVEY WITHOUT COMPLETION, PLEASE SKIP THIS ONE! (No worries! We'll send more)",
  },
  {
    alertId: 65,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Monday 1 5:17 PM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_m1_517",
    message: null,
  },
  {
    alertId: 66,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Monday 1 8:46 PM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_m1_846",
    message: null,
  },
  {
    alertId: 67,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Tuesday 1 8:32 AM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_t1_832",
    message: null,
  },
  {
    alertId: 68,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Tuesday 1 6:34 PM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_t1_634",
    message: null,
  },
  {
    alertId: 69,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Tuesday 1 8:58 PM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_t1_858",
    message: null,
  },
  {
    alertId: 70,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Wednesday 1 8:12 AM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_w1_812",
    message: null,
  },
  {
    alertId: 71,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Wednesday 1 9:00 PM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_w1_900",
    message: null,
  },
  {
    alertId: 72,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Thursday 7:11 AM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_th_711",
    message: null,
  },
  {
    alertId: 73,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Thursday 5:32 PM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_th_532",
    message: null,
  },
  {
    alertId: 74,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Friday 9:00 AM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_f_900",
    message: null,
  },
  {
    alertId: 75,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Friday 7:04 PM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_f_704",
    message: null,
  },
  {
    alertId: 76,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Friday 8:41 PM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_f_841",
    message: null,
  },
  {
    alertId: 77,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Saturday 8:56 AM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_sa_856",
    message: null,
  },
  {
    alertId: 78,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Saturday 5:01 PM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_sa_501",
    message: null,
  },
  {
    alertId: 79,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Sunday 7:55 AM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_su_755",
    message: null,
  },
  {
    alertId: 80,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Sunday 6:01 PM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_su_601",
    message: null,
  },
  {
    alertId: 81,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Sunday 7:36 PM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_su_736",
    message: null,
  },
  {
    alertId: 82,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Monday 2 8:49 AM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_m2_849",
    message: null,
  },
  {
    alertId: 83,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Monday 2 8:09 PM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_m2_809",
    message: null,
  },
  {
    alertId: 84,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Tuesday 2 7:33 AM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_t2_733",
    message: null,
  },
  {
    alertId: 85,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Tuesday 2 5:12 PM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_t2_512",
    message: null,
  },
  {
    alertId: 86,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Wednesday 2 8:40 AM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_w2_840",
    message: null,
  },
  {
    alertId: 87,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Wednesday 2 6:01 PM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_w2_601",
    message: null,
  },
  {
    alertId: 88,
    wave: 2 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Wednesday 2 7:36 PM",
    trigger: null,
    condition: "[ema_y2_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y2_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y2_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_w2_736",
    message: null,
  },
  {
    alertId: 89,
    wave: 2 as WaveYear,
    kind: "sts2_invite",
    instrument: "Screen Time Auto Invite 2.1",
    trigger: null,
    condition: "[screen_time_2_y2_arm_1][screen_time_cycle_2]=1",
    sendDateSpec: "[screen_time_2_y2_arm_1][screen_time_2_1_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending a brief 2-3 minute at screen-time survey to complete. After completion of your first wave of the study, we are sending another 3 surveys before inviting you back in for the second wave! 7/9 [screen_time_2_y2_arm_1][survey-link:screen_time_1_2] THERE WILL BE DAILY AUTOMATED REMINDERS FOR THE NEXT WEEK UNTIL THE SURVEY IS COMPLETE",
  },
  {
    alertId: 90,
    wave: 2 as WaveYear,
    kind: "sts2_invite",
    instrument: "Screen Time Auto Invite 2.2",
    trigger: null,
    condition: "[screen_time_2_y2_arm_1][screen_time_cycle_2]=1",
    sendDateSpec: "[screen_time_2_y2_arm_1][screen_time_2_2_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending a brief 2-3 minute at screen-time survey to complete. After completion of your first wave of the study, we are sending another 3 surveys before inviting you back in for the second wave! 8/9 [screen_time_2_y2_arm_1][survey-link:screen_time_2_2]",
  },
  {
    alertId: 91,
    wave: 2 as WaveYear,
    kind: "sts2_invite",
    instrument: "Screen Time Auto Invite 2.3",
    trigger: null,
    condition: "[screen_time_2_y2_arm_1][screen_time_cycle_2]=1",
    sendDateSpec: "[screen_time_2_y2_arm_1][screen_time_2_3_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending a brief 2-3 minute at screen-time survey to complete. After completion of your first wave of the study, we are sending another 3 surveys before inviting you back in for the second wave! 9/9 [screen_time_2_y2_arm_1][survey-link:screen_time_3_2] THERE WILL BE DAILY AUTOMATED REMINDERS FOR THE NEXT WEEK UNTIL THE SURVEY IS COMPLETE",
  },
  {
    alertId: 93,
    wave: 2 as WaveYear,
    kind: "sts2_followup",
    instrument: "Screen Time Follow up 2.1",
    trigger: null,
    condition: "[screen_time_2_y2_arm_1][screen_time_cycle_2]=1\nAND\n[screen_time_2_y2_arm_1][screen_time_1_2_complete]<>2",
    sendDateSpec: "1 days after [screen_time_2_y2_arm_1][screen_time_2_1_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]",
    emaKey: null,
    message: "Hello, we just wanted to follow up about the screentime survey. Whenever you get the chance can you please fill out the survey? - [screen_time_2_y2_arm_1][survey-link:screen_time_1_2] If you opened the survey but are still receiving the message, it it because you likely left it incomplete - please restart the survey ( this is an automated reminder and it will send for the next week - feel free to respond and let us know if there is a reason you can't get to it this month)",
  },
  {
    alertId: 94,
    wave: 2 as WaveYear,
    kind: "sts2_followup",
    instrument: "Screen Time Follow up 2.2",
    trigger: null,
    condition: "[screen_time_2_y2_arm_1][screen_time_cycle_2]=1\nAND\n[screen_time_2_y2_arm_1][screen_time_2_2_complete]<>2",
    sendDateSpec: "1 days after [screen_time_2_y2_arm_1][screen_time_2_2_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]",
    emaKey: null,
    message: "Hello, we just wanted to follow up about the screentime survey. Whenever you get the chance can you please fill out the survey? - [screen_time_2_y2_arm_1][survey-link:screen_time_2_2] If you opened the survey but are still receiving the message, it it because you likely left it incomplete - please restart the survey ( this is an automated reminder and it will send for the next week - feel free to respond and let us know if there is a reason you can't get to it this month)",
  },
  {
    alertId: 95,
    wave: 2 as WaveYear,
    kind: "sts2_followup",
    instrument: "Screen Time Follow up 2.3",
    trigger: null,
    condition: "[screen_time_2_y2_arm_1][screen_time_cycle_2]=1\nAND\n[screen_time_2_y2_arm_1][screen_time_3_2_complete]<>2",
    sendDateSpec: "1 days after [screen_time_2_y2_arm_1][screen_time_2_3_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hello, we just wanted to follow up about the screentime survey. Whenever you get the chance can you please fill out the survey? - [screen_time_2_y2_arm_1][survey-link:screen_time_3_2] If you opened the survey but are still receiving the message, it it because you likely left it incomplete - please restart the survey ( this is an automated reminder and it will send for the next week - feel free to respond and let us know if there is a reason you can't get to it this month)",
  },
  {
    alertId: 287,
    wave: 2 as WaveYear,
    kind: "payment_email",
    instrument: "W2 STS-EMA Payment email",
    trigger: null,
    condition: "Wave 2 V2 complete\n\nAND\n\n[ema_y2_arm_1][ema_payment_redeem_yn]<>1  // not yet redeemed",
    sendDateSpec: "5 days after STS2.3 (the final screen-time-2 survey).",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]",
    emaKey: null,
    message: "Hi [preenrollment_arm_1][first_name]! \n\nThank you for completing Wave 2! Click this link to redeem your payment. If your payment is not redeemed before [expire_date] the link will expire.\n \n[ema_y2_arm_1][survey-link:ema_payment]",
  },
  {
    alertId: 289,
    wave: 2 as WaveYear,
    kind: "payment_followup",
    instrument: "W2 STS-EMA Payment Follow-Up",
    trigger: null,
    condition: "[ema_y2_arm_1][ema_payment_redeem_yn]<>1  // still not redeemed",
    sendDateSpec: "Every 2 weeks after the initial payment email, up to the expire date (3 months from initial).",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]",
    emaKey: null,
    message: "Hi [preenrollment_arm_1][first_name]! \n\nThis is an automated follow up message -- We noticed you still have not yet redeemed your bonus compensation for completing Wave 2. As a reminder, the compensation link will expire on [expire_date]. \n\n[ema_y2_arm_1][survey-link:ema_payment]",
  },
  {
    alertId: 290,
    wave: 2 as WaveYear,
    kind: "payment_expire",
    instrument: "W2 STS-EMA Payment Expired",
    trigger: null,
    condition: "[ema_y2_arm_1][ema_payment_redeem_yn]<>1  // expired without redeeming",
    sendDateSpec: "On the expire date (3 months after the initial payment email).",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]",
    emaKey: null,
    message: "Hi [preenrollment_arm_1][first_name]\n\nThis is an automated follow up message -- Your Wave 2 completion compensation link has expired. Please reach out to us and we will send you a new link.\n \nBest,\nProject LITe",
  },
  {
    alertId: 48,
    wave: 3 as WaveYear,
    kind: "sts1_invite",
    instrument: "Screen Time Auto Invite 1.1",
    trigger: null,
    condition: "[screen_time_y3_arm_1][screen_time_cycle_1]=1AND[screen_time_y3_arm_1][screen_time_1_complete]<>2",
    sendDateSpec: "[screen_time_y3_arm_1][screen_time_1_1_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending a brief 2-3 minute at screen-time survey to complete. We also want to remind you that for sticking with us and completing these surveys you will be compensated with $70 after 10 months. 1/9 [screen_time_y3_arm_1][survey-link:screen_time_1] THERE WILL BE DAILY AUTOMATED REMINDERS FOR THE NEXT WEEK UNTIL THE SURVEY IS COMPLETE",
  },
  {
    alertId: 49,
    wave: 3 as WaveYear,
    kind: "sts1_invite",
    instrument: "Screen Time Auto Invite 1.2",
    trigger: null,
    condition: "[screen_time_y3_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y3_arm_1][screen_time_2_complete]<>2",
    sendDateSpec: "[screen_time_y3_arm_1][screen_time_1_2_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending a brief 2-3 minute at screen-time survey to complete. We also want to remind you that for sticking with us and completing these surveys you will be compensated with $70 after 10 months. 2/9 [screen_time_y3_arm_1][survey-link:screen_time_2] THERE WILL BE DAILY AUTOMATED REMINDERS FOR THE NEXT WEEK UNTIL THE SURVEY IS COMPLETE",
  },
  {
    alertId: 50,
    wave: 3 as WaveYear,
    kind: "sts1_invite",
    instrument: "Screen Time Auto invite 1.3",
    trigger: null,
    condition: "[screen_time_y3_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y3_arm_1][screen_time_3_complete]<>2",
    sendDateSpec: "[screen_time_y3_arm_1][screen_time_1_3_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending a brief 2-3 minute at screen-time survey to complete. We also want to remind you that for sticking with us and completing these surveys you will be compensated with $70 after 10 months. 3/9 [screen_time_y3_arm_1][survey-link:screen_time_3] THERE WILL BE DAILY AUTOMATED REMINDERS FOR THE NEXT WEEK UNTIL THE SURVEY IS COMPLETE",
  },
  {
    alertId: 51,
    wave: 3 as WaveYear,
    kind: "sts1_invite",
    instrument: "Screen time Auto invite 1.4",
    trigger: null,
    condition: "[screen_time_y3_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y3_arm_1][screen_time_4_complete]<>2",
    sendDateSpec: "[screen_time_y3_arm_1][screen_time_1_4_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending a brief 2-3 minute at screen-time survey to complete. We also want to remind you that for sticking with us and completing these surveys you will be compensated with $70 after 10 months. 4/9 [screen_time_y3_arm_1][survey-link:screen_time_4] THERE WILL BE DAILY AUTOMATED REMINDERS FOR THE NEXT WEEK UNTIL THE SURVEY IS COMPLETE",
  },
  {
    alertId: 52,
    wave: 3 as WaveYear,
    kind: "sts1_invite",
    instrument: "Screen Time Auto Invite 1.5",
    trigger: null,
    condition: "[screen_time_y3_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y3_arm_1][screen_time_5_complete]<>2",
    sendDateSpec: "[screen_time_y3_arm_1][screen_time_1_5_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending a brief 2-3 minute at screen-time survey to complete. We also want to remind you that for sticking with us and completing these surveys you will be compensated with $70 after 10 months. 5/9 [screen_time_y3_arm_1][survey-link:screen_time_5] THERE WILL BE DAILY AUTOMATED REMINDERS FOR THE NEXT WEEK UNTIL THE SURVEY IS COMPLETE",
  },
  {
    alertId: 53,
    wave: 3 as WaveYear,
    kind: "sts1_invite",
    instrument: "Screen Time Auto Invite 1.6",
    trigger: null,
    condition: "[screen_time_y3_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y3_arm_1][screen_time_6_complete]<>2",
    sendDateSpec: "[screen_time_y3_arm_1][screen_time_1_6_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending a brief 2-3 minute at screen-time survey to complete. We also want to remind you that for sticking with us and completing these surveys you will be compensated with $70 after 10 months. 6/9 [screen_time_y3_arm_1][survey-link:screen_time_6] THERE WILL BE DAILY AUTOMATED REMINDERS FOR THE NEXT WEEK UNTIL THE SURVEY IS COMPLETE",
  },
  {
    alertId: 54,
    wave: 3 as WaveYear,
    kind: "sts1_followup",
    instrument: "Screen Time Follow Up 1.1",
    trigger: null,
    condition: "[screen_time_y3_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y3_arm_1][screen_time_1_complete]<>2",
    sendDateSpec: "1 days after [screen_time_y3_arm_1][screen_time_1_1_date].   Repeat every day  Send up to 6 times total",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hello, we just wanted to follow up about the screentime survey. Whenever you get the chance can you please fill out the survey? - [screen_time_y3_arm_1][survey-link:screen_time_1] If you opened the survey but are still receiving the message, it it because you likely left it incomplete - please restart the survey ( this is an automated reminder and it will send for the next week - feel free to respond and let us know if there is a reason you can't get to it this month)",
  },
  {
    alertId: 55,
    wave: 3 as WaveYear,
    kind: "sts1_followup",
    instrument: "Screen Time Follow Up 1.2",
    trigger: null,
    condition: "[screen_time_y3_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y3_arm_1][screen_time_2_complete]<>2",
    sendDateSpec: "1 days after [screen_time_y3_arm_1][screen_time_1_2_date].   Repeat every day  Send up to 6 times total",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hello, we just wanted to follow up about the screentime survey. Whenever you get the chance can you please fill out the survey? [screen_time_y3_arm_1][survey-link:screen_time_2] If you opened the survey but are still receiving the message, it it because you likely left it incomplete - please restart the survey ( this is an automated reminder and it will send for the next week - feel free to respond and let us know if there is a reason you can't get to it this month)",
  },
  {
    alertId: 56,
    wave: 3 as WaveYear,
    kind: "sts1_followup",
    instrument: "Screen Time Follow Up 1.3",
    trigger: null,
    condition: "[screen_time_y3_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y3_arm_1][screen_time_3_complete]<>2",
    sendDateSpec: "1 days after [screen_time_y3_arm_1][screen_time_1_3_date].   Repeat every day  Send up to 6 times total",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hello, we just wanted to follow up about the screentime survey. Whenever you get the chance can you please fill out the survey? [screen_time_y3_arm_1][survey-link:screen_time_3] If you opened the survey but are still receiving the message, it it because you likely left it incomplete - please restart the survey. ( this is an automated reminder and it will send for the next week - feel free to respond and let us know if there is a reason you can't get to it this month)",
  },
  {
    alertId: 57,
    wave: 3 as WaveYear,
    kind: "sts1_followup",
    instrument: "Screen Time Follow Up 1.4",
    trigger: null,
    condition: "[screen_time_y3_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y3_arm_1][screen_time_4_complete]<>2",
    sendDateSpec: "1 days after [screen_time_y3_arm_1][screen_time_1_4_date].   Repeat every day  Send up to 6 times total",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hello, we just wanted to follow up about the screentime survey. Whenever you get the chance can you please fill out the survey? [screen_time_y3_arm_1][survey-link:screen_time_4] If you opened the survey but are still receiving the message, it it because you likely left it incomplete - please restart the survey.",
  },
  {
    alertId: 58,
    wave: 3 as WaveYear,
    kind: "sts1_followup",
    instrument: "Screen Time Follow Up 1.5",
    trigger: null,
    condition: "[screen_time_y3_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y3_arm_1][screen_time_5_complete]<>2",
    sendDateSpec: "1 days after [screen_time_y3_arm_1][screen_time_1_5_date].   Repeat every day  Send up to 6 times total",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hello, we just wanted to follow up about the screentime survey. Whenever you get the chance can you please fill out the survey? [screen_time_y3_arm_1][survey-link:screen_time_5] If you opened the survey but are still receiving the message, it it because you likely left it incomplete - please restart the survey. ( this is an automated reminder and it will send for the next week - feel free to respond and let us know if there is a reason you can't get to it this month)",
  },
  {
    alertId: 59,
    wave: 3 as WaveYear,
    kind: "sts1_followup",
    instrument: "Screen Time Follow Up 1.6",
    trigger: null,
    condition: "[screen_time_y3_arm_1][screen_time_cycle_1]=1\nAND\n[screen_time_y3_arm_1][screen_time_6_complete]<>2",
    sendDateSpec: "1 days after [screen_time_y3_arm_1][screen_time_1_6_date].   Repeat every day  Send up to 6 times total",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hello, we just wanted to follow up about the screentime survey. Whenever you get the chance can you please fill out the survey? [screen_time_y3_arm_1][survey-link:screen_time_6] If you opened the survey but are still receiving the message, it it because you likely left it incomplete - please restart the survey ( this is an automated reminder and it will send for the next week - feel free to respond and let us know if there is a reason you can't get to it this month)",
  },
  {
    alertId: 60,
    wave: 3 as WaveYear,
    kind: "athome_sms",
    instrument: "At-Home Survey Send (Text)",
    trigger: null,
    condition: "[visit_1_y3_arm_1][break_1_complete]=2",
    sendDateSpec: "3 hours, 45 minutes after [visit_1_y3_arm_1][timestamp_athome]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]\t[email]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending an 8 section, 10-15 minute at-home survey section to complete. We will reach out to schedule the second visit once this survey has been completed: [athome_measures_y3_arm_1][survey-link:texi]",
  },
  {
    alertId: 61,
    wave: 3 as WaveYear,
    kind: "athome_email",
    instrument: "At-Home Survey Send (Email)",
    trigger: null,
    condition: "[visit_1_y3_arm_1][break_1_complete]=2",
    sendDateSpec: "3 hours, 45 minutes after [visit_1_y3_arm_1][timestamp_athome]",
    destinationSpec: "[preenrollment_arm_1][email]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending an 8 section, 10-15 minute at-home survey section to complete. We will reach out to schedule the second visit once this survey has been completed: [athome_measures_y3_arm_1][survey-link:texi] Project LITe Team",
  },
  {
    alertId: 63,
    wave: 3 as WaveYear,
    kind: "ema_enable",
    instrument: "EMA Y1 Enable",
    trigger: "4 months after invite 1.6 on the first 1st of the month",
    condition: "// Fires BEFORE the participant has enabled. The enable survey is where they set\n// [ema_y3_arm_1][lite_server_ema_enable] (the enable field) AND choose\n// [ema_y3_arm_1][ema_phone] — the phone number they want the EMA texts sent to.\n[ema_y3_arm_1][lite_server_ema_enable]<>1  // not yet enabled",
    sendDateSpec: "3 days, 8 hours before [ema_y3_arm_1][ema_start_day]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]",
    emaKey: null,
    message: "Hi [preenrollment_arm_1][first_name]! This is the project LITe Team.\n\n\nWe are beginning our social check next week on Monday. This will be a 10 day period, where we will be sending you 2 or 3 surveys a day, at random times. If you complete enough of them we will send you 70 dollars.\n\n\nPLEASE CLICK THIS LINK TO ENABLE THE SOCIAL CHECK:  [ema_y3_arm_1][survey-link:ema_participant_confirmation]",
  },
  {
    alertId: 64,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Monday 1 7:34 AM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: "[ema_y3_arm_1][ema_m1_734]",
    destinationSpec: "[ema_y3_arm_1][ema_phone]",
    emaKey: "ema_m1_734",
    message: "Hi [preenrollment_arm_1][first_name]!\n\nThis is a PROJECT LITe social check survey! It is meant to gauge your experience at this moment - and should only take 2-3 minutes to complete!\n\n\n\n[ema_y3_arm_1][survey-link:ema_report_1]\n\n\n**IF 30 MINUTES HAS PASSED SINCE YOU RECEIVED THIS SURVEY WITHOUT COMPLETION, PLEASE SKIP THIS ONE! (No worries! We'll send more)",
  },
  {
    alertId: 65,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Monday 1 5:17 PM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_m1_517",
    message: null,
  },
  {
    alertId: 66,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Monday 1 8:46 PM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_m1_846",
    message: null,
  },
  {
    alertId: 67,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Tuesday 1 8:32 AM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_t1_832",
    message: null,
  },
  {
    alertId: 68,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Tuesday 1 6:34 PM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_t1_634",
    message: null,
  },
  {
    alertId: 69,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Tuesday 1 8:58 PM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_t1_858",
    message: null,
  },
  {
    alertId: 70,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Wednesday 1 8:12 AM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_w1_812",
    message: null,
  },
  {
    alertId: 71,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Wednesday 1 9:00 PM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_w1_900",
    message: null,
  },
  {
    alertId: 72,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Thursday 7:11 AM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_th_711",
    message: null,
  },
  {
    alertId: 73,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Thursday 5:32 PM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_th_532",
    message: null,
  },
  {
    alertId: 74,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Friday 9:00 AM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_f_900",
    message: null,
  },
  {
    alertId: 75,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Friday 7:04 PM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_f_704",
    message: null,
  },
  {
    alertId: 76,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Friday 8:41 PM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_f_841",
    message: null,
  },
  {
    alertId: 77,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Saturday 8:56 AM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_sa_856",
    message: null,
  },
  {
    alertId: 78,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Saturday 5:01 PM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_sa_501",
    message: null,
  },
  {
    alertId: 79,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Sunday 7:55 AM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_su_755",
    message: null,
  },
  {
    alertId: 80,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Sunday 6:01 PM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_su_601",
    message: null,
  },
  {
    alertId: 81,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Sunday 7:36 PM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_su_736",
    message: null,
  },
  {
    alertId: 82,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Monday 2 8:49 AM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_m2_849",
    message: null,
  },
  {
    alertId: 83,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Monday 2 8:09 PM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_m2_809",
    message: null,
  },
  {
    alertId: 84,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Tuesday 2 7:33 AM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_t2_733",
    message: null,
  },
  {
    alertId: 85,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Tuesday 2 5:12 PM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_t2_512",
    message: null,
  },
  {
    alertId: 86,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Wednesday 2 8:40 AM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_w2_840",
    message: null,
  },
  {
    alertId: 87,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Wednesday 2 6:01 PM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_w2_601",
    message: null,
  },
  {
    alertId: 88,
    wave: 3 as WaveYear,
    kind: "ema_prompt",
    instrument: "EMA.1.1 Wednesday 2 7:36 PM",
    trigger: null,
    condition: "[ema_y3_arm_1][lite_server_ema_enable]=1  // participant enabled the social check via the enable survey\nAND\n[ema_y3_arm_1][ema_start_day_calc]<1  // the EMA start day has arrived\nAND\n// this prompt\u2019s response not yet submitted (ema_report_N_complete<>2)\n// Sent to [ema_y3_arm_1][ema_phone] \u2014 the number the participant chose in the enable survey.",
    sendDateSpec: null,
    destinationSpec: null,
    emaKey: "ema_w2_736",
    message: null,
  },
  {
    alertId: 89,
    wave: 3 as WaveYear,
    kind: "sts2_invite",
    instrument: "Screen Time Auto Invite 2.1",
    trigger: null,
    condition: "[screen_time_2_y3_arm_1][screen_time_cycle_2]=1",
    sendDateSpec: "[screen_time_2_y3_arm_1][screen_time_2_1_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending a brief 2-3 minute at screen-time survey to complete. After completion of your first wave of the study, we are sending another 3 surveys before inviting you back in for the second wave! 7/9 [screen_time_2_y3_arm_1][survey-link:screen_time_1_2] THERE WILL BE DAILY AUTOMATED REMINDERS FOR THE NEXT WEEK UNTIL THE SURVEY IS COMPLETE",
  },
  {
    alertId: 90,
    wave: 3 as WaveYear,
    kind: "sts2_invite",
    instrument: "Screen Time Auto Invite 2.2",
    trigger: null,
    condition: "[screen_time_2_y3_arm_1][screen_time_cycle_2]=1",
    sendDateSpec: "[screen_time_2_y3_arm_1][screen_time_2_2_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending a brief 2-3 minute at screen-time survey to complete. After completion of your first wave of the study, we are sending another 3 surveys before inviting you back in for the second wave! 8/9 [screen_time_2_y3_arm_1][survey-link:screen_time_2_2]",
  },
  {
    alertId: 91,
    wave: 3 as WaveYear,
    kind: "sts2_invite",
    instrument: "Screen Time Auto Invite 2.3",
    trigger: null,
    condition: "[screen_time_2_y3_arm_1][screen_time_cycle_2]=1",
    sendDateSpec: "[screen_time_2_y3_arm_1][screen_time_2_3_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]",
    emaKey: null,
    message: "Hi this is project LITe. This is for [preenrollment_arm_1][first_name]. We are sending a brief 2-3 minute at screen-time survey to complete. After completion of your first wave of the study, we are sending another 3 surveys before inviting you back in for the second wave! 9/9 [screen_time_2_y3_arm_1][survey-link:screen_time_3_2] THERE WILL BE DAILY AUTOMATED REMINDERS FOR THE NEXT WEEK UNTIL THE SURVEY IS COMPLETE",
  },
  {
    alertId: 93,
    wave: 3 as WaveYear,
    kind: "sts2_followup",
    instrument: "Screen Time Follow up 2.1",
    trigger: null,
    condition: "[screen_time_2_y3_arm_1][screen_time_cycle_2]=1\nAND\n[screen_time_2_y3_arm_1][screen_time_1_2_complete]<>2",
    sendDateSpec: "1 days after [screen_time_2_y3_arm_1][screen_time_2_1_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]",
    emaKey: null,
    message: "Hello, we just wanted to follow up about the screentime survey. Whenever you get the chance can you please fill out the survey? - [screen_time_2_y3_arm_1][survey-link:screen_time_1_2] If you opened the survey but are still receiving the message, it it because you likely left it incomplete - please restart the survey ( this is an automated reminder and it will send for the next week - feel free to respond and let us know if there is a reason you can't get to it this month)",
  },
  {
    alertId: 94,
    wave: 3 as WaveYear,
    kind: "sts2_followup",
    instrument: "Screen Time Follow up 2.2",
    trigger: null,
    condition: "[screen_time_2_y3_arm_1][screen_time_cycle_2]=1\nAND\n[screen_time_2_y3_arm_1][screen_time_2_2_complete]<>2",
    sendDateSpec: "1 days after [screen_time_2_y3_arm_1][screen_time_2_2_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]",
    emaKey: null,
    message: "Hello, we just wanted to follow up about the screentime survey. Whenever you get the chance can you please fill out the survey? - [screen_time_2_y3_arm_1][survey-link:screen_time_2_2] If you opened the survey but are still receiving the message, it it because you likely left it incomplete - please restart the survey ( this is an automated reminder and it will send for the next week - feel free to respond and let us know if there is a reason you can't get to it this month)",
  },
  {
    alertId: 95,
    wave: 3 as WaveYear,
    kind: "sts2_followup",
    instrument: "Screen Time Follow up 2.3",
    trigger: null,
    condition: "[screen_time_2_y3_arm_1][screen_time_cycle_2]=1\nAND\n[screen_time_2_y3_arm_1][screen_time_3_2_complete]<>2",
    sendDateSpec: "1 days after [screen_time_2_y3_arm_1][screen_time_2_3_date]",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]",
    emaKey: null,
    message: "Hello, we just wanted to follow up about the screentime survey. Whenever you get the chance can you please fill out the survey? - [screen_time_2_y3_arm_1][survey-link:screen_time_3_2] If you opened the survey but are still receiving the message, it it because you likely left it incomplete - please restart the survey ( this is an automated reminder and it will send for the next week - feel free to respond and let us know if there is a reason you can't get to it this month)",
  },
  {
    alertId: 287,
    wave: 3 as WaveYear,
    kind: "payment_email",
    instrument: "W3 STS-EMA Payment email",
    trigger: null,
    condition: "Wave 3 V2 complete\n\nAND\n\n[ema_y3_arm_1][ema_payment_redeem_yn]<>1  // not yet redeemed",
    sendDateSpec: "5 days after STS2.3 (the final screen-time-2 survey).",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]",
    emaKey: null,
    message: "Hi [preenrollment_arm_1][first_name]! \n\nThank you for completing Wave 3! Click this link to redeem your payment. If your payment is not redeemed before [expire_date] the link will expire.\n \n[ema_y3_arm_1][survey-link:ema_payment]",
  },
  {
    alertId: 289,
    wave: 3 as WaveYear,
    kind: "payment_followup",
    instrument: "W3 STS-EMA Payment Follow-Up",
    trigger: null,
    condition: "[ema_y3_arm_1][ema_payment_redeem_yn]<>1  // still not redeemed",
    sendDateSpec: "Every 2 weeks after the initial payment email, up to the expire date (3 months from initial).",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]",
    emaKey: null,
    message: "Hi [preenrollment_arm_1][first_name]! \n\nThis is an automated follow up message -- We noticed you still have not yet redeemed your bonus compensation for completing Wave 3. As a reminder, the compensation link will expire on [expire_date]. \n\n[ema_y3_arm_1][survey-link:ema_payment]",
  },
  {
    alertId: 290,
    wave: 3 as WaveYear,
    kind: "payment_expire",
    instrument: "W3 STS-EMA Payment Expired",
    trigger: null,
    condition: "[ema_y3_arm_1][ema_payment_redeem_yn]<>1  // expired without redeeming",
    sendDateSpec: "On the expire date (3 months after the initial payment email).",
    destinationSpec: "[preenrollment_arm_1][phone_primary]; [preenrollment_arm_1][phone_secondary]",
    emaKey: null,
    message: "Hi [preenrollment_arm_1][first_name]\n\nThis is an automated follow up message -- Your Wave 3 completion compensation link has expired. Please reach out to us and we will send you a new link.\n \nBest,\nProject LITe",
  },
];

export const TIMELINE_ALERTS: TimelineAlert[] = RAW.map((a) => ({
  ...a,
  channels: parseChannels(a.destinationSpec),
}));

export function alertsForWave(wave: WaveYear): TimelineAlert[] {
  return TIMELINE_ALERTS.filter((a) => a.wave === wave);
}

export function alertById(alertId: number, wave: WaveYear): TimelineAlert | undefined {
  return TIMELINE_ALERTS.find((a) => a.alertId === alertId && a.wave === wave);
}

// Wave 1 uses the same schedule as Wave 2 (the team treats Y1 as the
// canonical template). Fetch-time field bindings rewrite the event slug.
export function alertsForRuntimeWave(wave: WaveYear): TimelineAlert[] {
  return TIMELINE_ALERTS.filter((a) => a.wave === (wave === 3 ? 3 : 2));
}
