#!/usr/bin/env node
/**
 * Fetch Project LITe data from REDCap → static JSON for the dashboard.
 *
 * Runs in GitHub Actions (Temple REDCap blocks Vercel IPs). On success
 * writes:
 *
 *   private/data/participants.json     — pivoted per-participant view
 *   private/data/due-reminders.json    — next 7 days of scheduled sends
 *   private/data/last-fetch.json       — { ok, timestamp, counts }
 *
 * Env vars required:
 *   REDCAP_API_URL          (defaults to Temple's URL)
 *   REDCAP_LITE_TOKEN       (project API token)
 *
 * Re-uses the SDN refresh-data pattern: retries on transient network
 * errors, batches surveyLink calls with concurrency cap.
 */

import fs from "fs";
import path from "path";
import crypto from "crypto";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR = path.join(__dirname, "..", "private", "data");

const REDCAP_API_URL = process.env.REDCAP_API_URL || "https://cphapps.temple.edu/redcap/api/";
const LITE_TOKEN = process.env.REDCAP_LITE_TOKEN;
const GOOGLE_SHEET_ID = process.env.LITE_GOOGLE_SHEET_ID || "18LScSoBcT8XmwA_WjfeN4Lt2PZESDm7FycAqocZ1cH4";
const GOOGLE_SA_JSON = process.env.GOOGLE_SERVICE_ACCOUNT_JSON;  // full JSON string

if (!LITE_TOKEN) {
  console.error("Missing REDCAP_LITE_TOKEN env var.");
  process.exit(1);
}

const WAVES = [1, 2, 3];

// Canonical event names per the Timeline workbook + REDCap metadata.
function eventName(kind, wave) {
  switch (kind) {
    case "pre":     return "preenrollment_arm_1";
    case "enroll":  return "enrollment_arm_1";
    case "v1":      return `visit_1_y${wave}_arm_1`;
    case "athome":  return `athome_measures_y${wave}_arm_1`;
    case "sts1":    return `screen_time_y${wave}_arm_1`;
    case "sts2":    return `screen_time_2_y${wave}_arm_1`;
    case "ema":     return `ema_y${wave}_arm_1`;
    case "v2":      return `visit_2_y${wave}_arm_1`;
    default: throw new Error(`Unknown event kind ${kind}`);
  }
}

// All EMA prompt field names — kept in sync with the keys generated by
// scripts/regen-timeline.py (Monday week 1 = ema_m1_734, etc.).
const EMA_PROMPT_FIELDS = [
  "ema_m1_734", "ema_m1_517", "ema_m1_846",
  "ema_t1_832", "ema_t1_634", "ema_t1_858",
  "ema_w1_812", "ema_w1_900",
  "ema_th_711", "ema_th_532",
  "ema_f_900",  "ema_f_704",  "ema_f_841",
  "ema_sa_856", "ema_sa_501",
  "ema_su_755", "ema_su_601", "ema_su_736",
  "ema_m2_849", "ema_m2_809",
  "ema_t2_733", "ema_t2_512",
  "ema_w2_840", "ema_w2_601", "ema_w2_736",
];

function parseCSV(text) {
  const lines = text.trim().split("\n");
  if (lines.length < 2) return [];
  const parseRow = (line) => {
    const result = [];
    let cur = "", inQuotes = false;
    for (let i = 0; i < line.length; i++) {
      const ch = line[i];
      if (ch === '"') {
        if (inQuotes && line[i + 1] === '"') { cur += '"'; i++; }
        else inQuotes = !inQuotes;
      } else if (ch === "," && !inQuotes) { result.push(cur); cur = ""; }
      else cur += ch;
    }
    result.push(cur);
    return result;
  };
  const headers = parseRow(lines[0]);
  const rows = [];
  for (let i = 1; i < lines.length; i++) {
    if (!lines[i].trim()) continue;
    const vals = parseRow(lines[i]);
    const r = {};
    for (let j = 0; j < headers.length; j++) r[headers[j]] = vals[j] ?? "";
    rows.push(r);
  }
  return rows;
}

async function redcapPost(params, attempt = 1) {
  const body = new URLSearchParams({ token: LITE_TOKEN, ...params });
  try {
    const res = await fetch(REDCAP_API_URL, {
      method: "POST", body,
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      signal: AbortSignal.timeout(60_000),
    });
    if (!res.ok) throw new Error(`REDCap error ${res.status}: ${await res.text()}`);
    return await res.text();
  } catch (err) {
    const transient = /timeout|fetch failed|ECONNRESET|ETIMEDOUT|ENOTFOUND|EAI_AGAIN|UND_ERR/i.test(String(err));
    if (transient && attempt < 3) {
      const delay = 2000 * attempt;
      console.warn(`  REDCap transient error (attempt ${attempt}): ${err.message || err}. Retrying in ${delay}ms…`);
      await new Promise(r => setTimeout(r, delay));
      return redcapPost(params, attempt + 1);
    }
    throw err;
  }
}

// Chunked record fetch — LITe is large enough that a single bulk export
// blows out REDCap's server memory. We loop per-event and stream each
// chunk straight into the per-record bucket so we never hold more than
// one event's worth of raw rows in memory at once.
async function fetchAllRecordsStreaming(byRecord) {
  const events = [eventName("pre"), eventName("enroll")];
  for (const w of WAVES) {
    for (const k of ["v1", "athome", "sts1", "sts2", "ema", "v2"]) {
      events.push(eventName(k, w));
    }
  }
  console.log(`  Will fetch ${events.length} events in series…`);
  let total = 0;
  for (const evt of events) {
    try {
      const csv = await redcapPost({
        content: "record", format: "csv", type: "flat",
        rawOrLabel: "raw", rawOrLabelHeaders: "raw",
        exportSurveyFields: "true",
        "events[0]": evt,
      });
      const rows = parseCSV(csv);
      console.log(`    ${evt}: ${rows.length} rows`);
      total += rows.length;
      for (const r of rows) {
        const id = r.record_id;
        if (!id) continue;
        if (!byRecord[id]) byRecord[id] = [];
        byRecord[id].push(r);
      }
    } catch (err) {
      console.warn(`    ${evt}: SKIPPED (${err.message})`);
    }
  }
  return total;
}

async function fetchSurveyLink(recordId, evtName, instrument) {
  try {
    const txt = await redcapPost({
      content: "surveyLink", format: "json",
      record: recordId, event: evtName, instrument,
    });
    const t = txt.trim();
    return t.startsWith("http") ? t : null;
  } catch { return null; }
}

async function batchAsync(tasks, concurrency = 3, delayMs = 200) {
  const out = [];
  for (let i = 0; i < tasks.length; i += concurrency) {
    const batch = tasks.slice(i, i + concurrency);
    const res = await Promise.all(batch.map(f => f()));
    out.push(...res);
    if (i + concurrency < tasks.length) {
      await new Promise(r => setTimeout(r, delayMs));
    }
  }
  return out;
}

function num(s) {
  const n = parseInt(s ?? "", 10);
  return isNaN(n) ? 0 : n;
}

function dayLabelForKey(k) {
  const m = k.match(/^ema_(m|t|w|th|f|sa|su)(\d?)_/);
  if (!m) return k;
  const day = { m: "Monday", t: "Tuesday", w: "Wednesday", th: "Thursday", f: "Friday", sa: "Saturday", su: "Sunday" }[m[1]];
  return m[2] ? `${day} ${m[2]}` : day;
}

function timeLabelForKey(k) {
  const m = k.match(/_(\d{3,4})$/);
  if (!m) return "";
  const t = m[1];
  const hh = parseInt(t.slice(0, t.length - 2), 10);
  const mm = t.slice(-2);
  const period = hh < 12 ? "AM" : "PM";
  const h12 = hh === 0 ? 12 : hh > 12 ? hh - 12 : hh;
  return `${h12}:${mm} ${period}`;
}

function pivotParticipant(recordRows) {
  if (recordRows.length === 0) return null;
  const recordId = recordRows[0].record_id;

  const byEvent = {};
  for (const r of recordRows) byEvent[r.redcap_event_name || ""] = r;

  // ONLY count someone as a participant once they have an enrollment row —
  // preenrollment alone is just a signup form, ~3x more rows than real
  // enrollees, and is what was polluting the dashboard's contact display.
  const enroll = byEvent[eventName("enroll")];
  if (!enroll) return null;

  // Pull contact info from enrollment, falling back to preenrollment.
  const pre = byEvent[eventName("pre")] || {};
  const pick = (field) => enroll[field] || pre[field] || "";
  const contact = {
    firstName: pick("first_name"),
    lastName: pick("last_name"),
    parentName: pick("parent_name"),
    email: pick("email"),
    phonePrimary: pick("phone_primary"),
    phoneSecondary: pick("phone_secondary"),
    childPhone: pick("child_phone"),
    // Cohort group is derivable from the record_id range: 1-999 -> "Y1 cohort",
    // 1000-1999 -> "Y2 cohort", 2000+ -> "Y3 cohort" per the session-notes
    // workbook convention. Keep the raw record_id range as the label.
    cohortGroup: pick("cohort_group") || pick("tppid") || "",
  };
  // The friendly PID for coordinators is the REDCap record_id (1-3160 range).
  const pid = String(recordId);

  const waves = {};
  let activeWave = null;
  for (const w of WAVES) {
    const v1 = byEvent[eventName("v1", w)];
    const athome = byEvent[eventName("athome", w)];
    const sts1 = byEvent[eventName("sts1", w)];
    const sts2 = byEvent[eventName("sts2", w)];
    const ema = byEvent[eventName("ema", w)];
    const v2 = byEvent[eventName("v2", w)];

    if (!v1 && !athome && !sts1 && !sts2 && !ema && !v2) continue;

    const buildVisit = (row) => {
      if (!row) return null;
      const forms = {};
      for (const k of Object.keys(row)) {
        if (k.endsWith("_complete")) forms[k.replace(/_complete$/, "")] = num(row[k]);
      }
      const allComplete = Object.values(forms).length > 0 && Object.values(forms).every(v => v === 2);
      return { date: row.visit_date || row.scheduled_date || null, forms, allComplete };
    };

    const buildSTS = (row, count) => {
      if (!row) return null;
      const cycles = [];
      // STS1 dates: screen_time_1_1_date … screen_time_1_6_date
      // STS1 complete: screen_time_1_complete … screen_time_6_complete
      // STS2 dates: screen_time_2_1_date … screen_time_2_3_date
      // STS2 complete: screen_time_1_2_complete, screen_time_2_2_complete,
      //   screen_time_3_2_complete  (the "_2_" suffix marks the STS2 instrument).
      // This matches REDCap reports 8040 (Y1) / 8430 (Y2) used by the legacy
      // followup_download scripts.
      const which = count === 6 ? "1" : "2";
      for (let i = 1; i <= count; i++) {
        const datefield = `screen_time_${which}_${i}_date`;
        const compField = which === "1"
          ? `screen_time_${i}_complete`
          : `screen_time_${i}_2_complete`;
        cycles.push({
          index: i,
          date: row[datefield] || null,
          complete: num(row[compField]),
          surveyLink: null,
        });
      }
      return {
        active: row[`screen_time_cycle_${which}`] === "1",
        cycles,
      };
    };

    const buildEMA = (row) => {
      if (!row) return null;
      const prompts = EMA_PROMPT_FIELDS.map(k => ({
        key: k,
        dayLabel: dayLabelForKey(k),
        timeLabel: timeLabelForKey(k),
        scheduledAt: row[k] || null,
        complete: num(row[`${k}_complete`] || row.ema_response_complete) === 2,
      }));
      return {
        active: row.ema_cycle === "1",
        startDay: row.ema_start_day || null,
        startDayCalc: row.ema_start_day_calc ? Number(row.ema_start_day_calc) : null,
        enableSent: false,
        phone: row.ema_phone || contact.phonePrimary,
        prompts,
      };
    };

    waves[w] = {
      year: w,
      v1: buildVisit(v1),
      atHome: athome ? {
        timestamp: athome.timestamp_athome || null,
        break1Complete: num(athome.break_1_complete),
        athomeMeasuresComplete: num(athome.athome_measures_complete),
      } : null,
      sts1: buildSTS(sts1, 6),
      sts2: buildSTS(sts2, 3),
      ema: buildEMA(ema),
      v2: buildVisit(v2),
    };

    if (waves[w].v1 && !waves[w].v2?.allComplete) activeWave = w;
  }

  return {
    pid,
    recordId,
    contact,
    waves,
    activeWave,
  };
}

// REDCap returns dates in several flavours: "YYYY-MM-DD",
// "YYYY-MM-DD HH:MM", "YYYY-MM-DD HH:MM:SS". Coerce to ISO and ignore
// anything we can't parse so a single bad row doesn't tank the whole run.
function toEpoch(s, defaultHour = 9) {
  if (!s) return null;
  // Strip whatever time the row had so we can attach our own default-hour.
  const dateOnly = String(s).slice(0, 10);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(dateOnly)) {
    // Already has time component or in an unknown shape — try direct parse.
    const direct = new Date(s).getTime();
    return isFinite(direct) ? direct : null;
  }
  const hh = String(defaultHour).padStart(2, "0");
  const t = new Date(`${dateOnly}T${hh}:00:00`).getTime();
  return isFinite(t) ? t : null;
}

function safeIso(epoch) {
  if (!isFinite(epoch)) return null;
  try { return new Date(epoch).toISOString(); } catch { return null; }
}

function computeDueReminders(participants) {
  const out = [];
  const now = Date.now();
  const horizon = now + 7 * 24 * 3600 * 1000;
  for (const p of participants) {
    for (const w of WAVES) {
      const wave = p.waves[w];
      if (!wave) continue;

      wave.sts1?.cycles.forEach((c, idx) => {
        const t = toEpoch(c.date);
        if (t == null || t < now || t > horizon) return;
        const iso = safeIso(t); if (!iso) return;
        out.push({
          pid: p.pid, recordId: p.recordId, wave: w,
          alertId: 48 + idx, kind: "sts1_invite",
          instrument: `Screen Time Auto Invite 1.${idx + 1}`,
          scheduledAt: iso,
          complete: c.complete === 2,
        });
      });
      wave.sts2?.cycles.forEach((c, idx) => {
        const t = toEpoch(c.date);
        if (t == null || t < now || t > horizon) return;
        const iso = safeIso(t); if (!iso) return;
        out.push({
          pid: p.pid, recordId: p.recordId, wave: w,
          alertId: 89 + idx, kind: "sts2_invite",
          instrument: `Screen Time Auto Invite 2.${idx + 1}`,
          scheduledAt: iso,
          complete: c.complete === 2,
        });
      });
      wave.ema?.prompts.forEach(prompt => {
        if (!prompt.scheduledAt) return;
        const t = new Date(prompt.scheduledAt).getTime();
        if (!isFinite(t) || t < now || t > horizon) return;
        const iso = safeIso(t); if (!iso) return;
        out.push({
          pid: p.pid, recordId: p.recordId, wave: w,
          alertId: 64, kind: "ema_prompt",
          emaKey: prompt.key,
          instrument: `EMA ${prompt.dayLabel} ${prompt.timeLabel}`,
          scheduledAt: iso,
          complete: prompt.complete,
        });
      });
      if (wave.atHome?.timestamp && wave.atHome.break1Complete === 2) {
        const base = new Date(wave.atHome.timestamp).getTime();
        if (!isFinite(base)) continue;
        const t = base + (3 * 60 + 45) * 60 * 1000;
        if (t >= now && t <= horizon) {
          const iso = safeIso(t); if (!iso) continue;
          out.push({
            pid: p.pid, recordId: p.recordId, wave: w,
            alertId: 60, kind: "athome_sms",
            instrument: "At-Home Survey Send (Text)",
            scheduledAt: iso,
            complete: wave.atHome.athomeMeasuresComplete === 2,
          });
          out.push({
            pid: p.pid, recordId: p.recordId, wave: w,
            alertId: 61, kind: "athome_email",
            instrument: "At-Home Survey Send (Email)",
            scheduledAt: iso,
            complete: wave.atHome.athomeMeasuresComplete === 2,
          });
        }
      }
    }
  }
  out.sort((a, b) => a.scheduledAt.localeCompare(b.scheduledAt));
  return out;
}

// --- Google Sheets read (PID Session Notes) ---
//
// The Excel mirror is /Users/dannyzweben/Downloads/0.LITe.1_PID_sessionnotes.xlsx.
// Tabs we care about:
//   Follow up.1 — Y1 follow-up: header row 3, V2 date col N, STS1 P-U, STS2 AB-AD, EMA W/X
//   Follow up.2 — Y2 follow-up: header row 8, V2 date col M, STS1 O-T, STS2 AB-AD, EMA W/X
//
// We index by PID and merge into participants[].waves[N].followupSheet so the
// dashboard can show V1/V2 completion the team manually tracks here.

function base64url(buf) {
  return Buffer.from(buf).toString("base64").replace(/=+$/, "").replace(/\+/g, "-").replace(/\//g, "_");
}

async function googleAccessToken() {
  if (!GOOGLE_SA_JSON) return null;
  let sa;
  try { sa = JSON.parse(GOOGLE_SA_JSON); }
  catch { console.warn("  ! GOOGLE_SERVICE_ACCOUNT_JSON not valid JSON"); return null; }

  const now = Math.floor(Date.now() / 1000);
  const header = base64url(JSON.stringify({ alg: "RS256", typ: "JWT" }));
  const claims = base64url(JSON.stringify({
    iss: sa.client_email,
    scope: "https://www.googleapis.com/auth/spreadsheets.readonly",
    aud: "https://oauth2.googleapis.com/token",
    exp: now + 3600,
    iat: now,
  }));
  const unsigned = `${header}.${claims}`;
  const signer = crypto.createSign("RSA-SHA256");
  signer.update(unsigned);
  const signature = base64url(signer.sign(sa.private_key));
  const jwt = `${unsigned}.${signature}`;

  const res = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      grant_type: "urn:ietf:params:oauth:grant-type:jwt-bearer",
      assertion: jwt,
    }),
  });
  if (!res.ok) {
    console.warn(`  ! Google auth ${res.status}: ${await res.text()}`);
    return null;
  }
  const { access_token } = await res.json();
  return access_token;
}

async function readSheetTab(accessToken, range) {
  const url = `https://sheets.googleapis.com/v4/spreadsheets/${GOOGLE_SHEET_ID}/values/${encodeURIComponent(range)}?majorDimension=ROWS&valueRenderOption=UNFORMATTED_VALUE`;
  const res = await fetch(url, { headers: { Authorization: `Bearer ${accessToken}` } });
  if (!res.ok) {
    console.warn(`  ! Sheet read ${range} ${res.status}: ${await res.text()}`);
    return [];
  }
  const data = await res.json();
  return data.values || [];
}

// Excel-style column letter → 0-based index. "A"=0, "Z"=25, "AA"=26, "AF"=31
function col(letter) {
  let n = 0;
  for (const ch of letter.toUpperCase()) n = n * 26 + (ch.charCodeAt(0) - 64);
  return n - 1;
}

function cell(row, letter) {
  const v = row[col(letter)];
  if (v === undefined || v === null || v === "") return null;
  return v;
}

// Returns true-ish if the cell holds a date or a non-empty value indicating
// the column has been actioned. Excel dates come back as ISO strings when we
// use UNFORMATTED_VALUE+sheet API, or numeric serial dates, or already-text.
function hasValue(v) {
  if (v === null || v === undefined) return false;
  if (typeof v === "string") return v.trim().length > 0;
  if (typeof v === "number") return v !== 0;
  return true;
}

async function fetchFollowupSheet() {
  if (!GOOGLE_SA_JSON) {
    console.log("  Skipping Google Sheets pull (GOOGLE_SERVICE_ACCOUNT_JSON not set)");
    return {};
  }
  const tok = await googleAccessToken();
  if (!tok) return {};

  // Follow up.1 (Y1) — header row 3, data from row 6 onward (rows 4-5 are notes/cohort marker).
  // Follow up.2 (Y2) — header row 8, data from row 11 onward.
  const followupByPid = {};

  const f1 = await readSheetTab(tok, "Follow up.1!A1:AZ700");
  for (let i = 5; i < f1.length; i++) {  // 0-indexed row 5 == sheet row 6
    const row = f1[i];
    if (!row?.length) continue;
    const pid = String(cell(row, "D") || "").trim().replace(/\.0$/, "");
    if (!pid || pid === "PID") continue;
    if (!followupByPid[pid]) followupByPid[pid] = {};
    followupByPid[pid].y1 = {
      record: cell(row, "A"),
      v2Date: cell(row, "N"),       // "Visit 2" date → V2Y1 complete if set
      sts1Months: [cell(row, "P"), cell(row, "Q"), cell(row, "R"), cell(row, "S"), cell(row, "T"), cell(row, "U")],
      emaDate: cell(row, "W"),
      emaStatus: cell(row, "X"),
      w1Comp: cell(row, "AA"),
      sts2Months: [cell(row, "AB"), cell(row, "AC"), cell(row, "AD")],
      wave2StartDate: cell(row, "AF"),
      raTag: cell(row, "L"),
      notes: cell(row, "I"),
    };
  }

  const f2 = await readSheetTab(tok, "Follow up.2!A1:AZ700");
  for (let i = 10; i < f2.length; i++) {  // header row 8, data row 11+
    const row = f2[i];
    if (!row?.length) continue;
    const pid = String(cell(row, "A") || "").trim().replace(/\.0$/, "");
    if (!pid || pid === "PID") continue;
    if (!followupByPid[pid]) followupByPid[pid] = {};
    followupByPid[pid].y2 = {
      record: cell(row, "B"),
      v2Date: cell(row, "M"),       // "WAVE 2, V2 Date" → V2Y2 complete if set
      sts1Months: [cell(row, "O"), cell(row, "P"), cell(row, "Q"), cell(row, "R"), cell(row, "S"), cell(row, "T")],
      emaDate: cell(row, "W"),
      emaStatus: cell(row, "X"),
      w2Comp: cell(row, "Z"),
      sts2Months: [cell(row, "AB"), cell(row, "AC"), cell(row, "AD")],
      wave3StartDate: cell(row, "AF"),
      notes: cell(row, "J"),
    };
  }

  console.log(`  Followup sheet: ${Object.keys(followupByPid).length} PIDs (` +
    `${Object.values(followupByPid).filter(x => x.y1).length} Y1, ` +
    `${Object.values(followupByPid).filter(x => x.y2).length} Y2)`);
  return followupByPid;
}

async function main() {
  console.log("=== LITe REDCap fetch ===");
  const byRecord = {};
  const total = await fetchAllRecordsStreaming(byRecord);
  console.log(`  Got ${total} REDCap rows, grouped into ${Object.keys(byRecord).length} records`);

  const participants = [];
  for (const recordRows of Object.values(byRecord)) {
    const p = pivotParticipant(recordRows);
    if (p) participants.push(p);
  }
  participants.sort((a, b) => a.pid.localeCompare(b.pid));
  console.log(`  Pivoted to ${participants.length} participants`);

  // Merge in Google Sheets data (Follow up.1 + .2)
  const followupByPid = await fetchFollowupSheet();
  let merged = 0;
  for (const p of participants) {
    const key = String(p.pid || "").replace(/\.0$/, "");
    const sheet = followupByPid[key];
    if (!sheet) continue;
    merged++;
    if (sheet.y1) {
      if (!p.waves[1]) p.waves[1] = { year: 1, v1: null, atHome: null, sts1: null, sts2: null, ema: null, v2: null };
      p.waves[1].followupSheet = sheet.y1;
      // Mark V2 complete if the V2 date is filled in.
      if (hasValue(sheet.y1.v2Date)) {
        if (!p.waves[1].v2) p.waves[1].v2 = { date: null, forms: {}, allComplete: false };
        p.waves[1].v2.date = String(sheet.y1.v2Date);
        p.waves[1].v2.allComplete = true;
      }
      // V1 done = exists in Follow up.1
      if (!p.waves[1].v1) p.waves[1].v1 = { date: null, forms: {}, allComplete: true };
      else p.waves[1].v1.allComplete = true;
    }
    if (sheet.y2) {
      if (!p.waves[2]) p.waves[2] = { year: 2, v1: null, atHome: null, sts1: null, sts2: null, ema: null, v2: null };
      p.waves[2].followupSheet = sheet.y2;
      if (hasValue(sheet.y2.v2Date)) {
        if (!p.waves[2].v2) p.waves[2].v2 = { date: null, forms: {}, allComplete: false };
        p.waves[2].v2.date = String(sheet.y2.v2Date);
        p.waves[2].v2.allComplete = true;
      }
      if (!p.waves[2].v1) p.waves[2].v1 = { date: null, forms: {}, allComplete: true };
      else p.waves[2].v1.allComplete = true;
    }
  }
  console.log(`  Merged followup-sheet data into ${merged} participants`);

  const linkTasks = [];
  for (const p of participants) {
    for (const w of WAVES) {
      const wave = p.waves[w];
      if (!wave) continue;
      if (wave.sts1?.active) {
        wave.sts1.cycles.forEach((c, idx) => {
          if (c.complete !== 2 && c.date) {
            linkTasks.push(async () => {
              c.surveyLink = await fetchSurveyLink(p.recordId, eventName("sts1", w), `screen_time_${idx + 1}`);
            });
          }
        });
      }
      if (wave.sts2?.active) {
        wave.sts2.cycles.forEach((c, idx) => {
          if (c.complete !== 2 && c.date) {
            linkTasks.push(async () => {
              c.surveyLink = await fetchSurveyLink(p.recordId, eventName("sts2", w), `screen_time_${idx + 1}_2`);
            });
          }
        });
      }
    }
  }
  console.log(`  Resolving ${linkTasks.length} survey links…`);
  await batchAsync(linkTasks, 3, 200);

  const due = computeDueReminders(participants);

  fs.mkdirSync(DATA_DIR, { recursive: true });
  fs.writeFileSync(path.join(DATA_DIR, "participants.json"), JSON.stringify({ participants, fetchedAt: new Date().toISOString() }, null, 2));
  fs.writeFileSync(path.join(DATA_DIR, "due-reminders.json"), JSON.stringify(due, null, 2));
  fs.writeFileSync(path.join(DATA_DIR, "last-fetch.json"), JSON.stringify({
    ok: true,
    timestamp: new Date().toISOString(),
    counts: {
      participants: participants.length,
      dueNext7Days: due.length,
    },
  }, null, 2));

  console.log(`✓ Wrote participants.json (${participants.length})`);
  console.log(`✓ Wrote due-reminders.json (${due.length} upcoming)`);
}

main().catch(err => {
  console.error("FATAL:", err.message);
  try {
    fs.mkdirSync(DATA_DIR, { recursive: true });
    fs.writeFileSync(path.join(DATA_DIR, "last-fetch.json"), JSON.stringify({
      ok: false,
      timestamp: new Date().toISOString(),
      error: err.message,
    }, null, 2));
  } catch {}
  process.exit(1);
});
